# Generated by Django 3.1.3 on 2020-11-22 09:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.UUID('50457b6a-90b4-4a9b-8f0d-4322c00cbd7d'), editable=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('article_number', models.TextField(max_length=50)),
                ('box_size', models.TextField(max_length=50)),
                ('for_age', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
