# Generated by Django 3.1.3 on 2020-11-22 13:39

from django.db import migrations, models
import django.db.models.deletion
import products.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20201122_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.UUID('624a8d7d-cf1e-43e0-9be4-c8dd13eb3ec8'), editable=False)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='box_size',
            field=models.CharField(blank=True, max_length=50, validators=[products.validators.validate_box_size]),
        ),
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c7bf8659-a7eb-4d20-9713-d991c1db73f0'), editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='for_age',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.age'),
        ),
        migrations.DeleteModel(
            name='Ages',
        ),
    ]
