# Generated by Django 3.1.3 on 2020-11-22 14:15

import cloudinary.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201122_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='age',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d6d29bc9-d298-497d-94d6-71eb50e33455'), editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('cf058388-c87f-4e37-a42b-64e303c0b7da'), editable=False),
        ),
    ]
